/**
 * Created by jason  on 16/7/14.
 * action类型
 */
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_RESULT_ACTION = 'LOGIN_RESULT_ACTION';


export const REGISTER_ACTION = 'REGISTER_ACTION';
export const RECOVER_ACTION = 'RECOVER_ACTION';
export const CONNECT_VPN_ACTION = 'CONNECT_VPN_ACTION';
export const VIP_DEPOSIT__ACTION = 'VIP_DEPOSIT__ACTION';
export const OPEN_FULL_PROXY__ACTION = 'OPEN_FULL_PROXY__ACTION';
export const DEPOSIT_SUCCESS_ACTION = 'DEPOSIT_SUCCESS_ACTION';
